# -*- coding: utf-8 -*-
"""day07_fibonacci

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ACjyx6LynQgAVxx2oTbug3ShLwzYKsVX
"""

# Day 7: Fibonacci Sequence Generator
# Author: Janani Thaddi

def fibonacci(n):
    """Return the first n Fibonacci numbers."""
    sequence = []
    a, b = 0, 1
    for _ in range(n):
        sequence.append(a)
        a, b = b, a + b
    return sequence


print("🌀 Welcome to Fibonacci Sequence Generator 🌀")

while True:
    print("\n1️⃣ Generate Fibonacci sequence")
    print("2️⃣ Save to file")
    print("3️⃣ Exit")

    choice = input("Enter your choice (1/2/3): ")

    if choice == "1":
        n = int(input("Enter how many numbers you want: "))
        fib_seq = fibonacci(n)
        print(f"\nThe first {n} Fibonacci numbers are:")
        print(fib_seq)

    elif choice == "2":
        n = int(input("Enter how many numbers you want to save: "))
        fib_seq = fibonacci(n)
        with open("fibonacci_sequence.txt", "w") as file:
            file.write(", ".join(map(str, fib_seq)))
        print("✅ Sequence saved to fibonacci_sequence.txt")

    elif choice == "3":
        print("👋 Goodbye! See you tomorrow!")
        break

    else:
        print("⚠️ Invalid choice. Try again!")

