# -*- coding: utf-8 -*-
"""day08_unit_converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rlr3z5d2J88-Rw4remWfyF1fUXBvgaaG
"""

# Day 8: Unit Converter
# Author: Janani Thaddi

def length_converter():
    print("\n📏 Length Converter")
    print("1. Meters to Kilometers")
    print("2. Kilometers to Miles")
    print("3. Miles to Feet")
    choice = input("Choose conversion type: ")

    if choice == "1":
        m = float(input("Enter meters: "))
        print(f"{m} meters = {m / 1000} kilometers")
    elif choice == "2":
        km = float(input("Enter kilometers: "))
        print(f"{km} kilometers = {km * 0.621371} miles")
    elif choice == "3":
        miles = float(input("Enter miles: "))
        print(f"{miles} miles = {miles * 5280} feet")
    else:
        print("❌ Invalid choice.")


def temperature_converter():
    print("\n🌡️ Temperature Converter")
    print("1. Celsius to Fahrenheit")
    print("2. Fahrenheit to Celsius")
    print("3. Celsius to Kelvin")
    choice = input("Choose conversion type: ")

    if choice == "1":
        c = float(input("Enter Celsius: "))
        print(f"{c}°C = {(c * 9/5) + 32}°F")
    elif choice == "2":
        f = float(input("Enter Fahrenheit: "))
        print(f"{f}°F = {(f - 32) * 5/9}°C")
    elif choice == "3":
        c = float(input("Enter Celsius: "))
        print(f"{c}°C = {c + 273.15}K")
    else:
        print("❌ Invalid choice.")


def weight_converter():
    print("\n⚖️ Weight Converter")
    print("1. Kilograms to Pounds")
    print("2. Pounds to Kilograms")
    print("3. Grams to Kilograms")
    choice = input("Choose conversion type: ")

    if choice == "1":
        kg = float(input("Enter kilograms: "))
        print(f"{kg} kg = {kg * 2.20462} pounds")
    elif choice == "2":
        lb = float(input("Enter pounds: "))
        print(f"{lb} pounds = {lb / 2.20462} kilograms")
    elif choice == "3":
        g = float(input("Enter grams: "))
        print(f"{g} grams = {g / 1000} kilograms")
    else:
        print("❌ Invalid choice.")


# Main menu
print("🌍 Welcome to the Unit Converter 🌍")

while True:
    print("\n1️⃣ Length Converter")
    print("2️⃣ Temperature Converter")
    print("3️⃣ Weight Converter")
    print("4️⃣ Exit")

    option = input("Select an option (1-4): ")

    if option == "1":
        length_converter()
    elif option == "2":
        temperature_converter()
    elif option == "3":
        weight_converter()
    elif option == "4":
        print("👋 Goodbye! See you on Day 9!")
        break
    else:
        print("⚠️ Invalid option. Try again.")

