# -*- coding: utf-8 -*-
"""day09_rock_paper_scissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18A-adxU7RHuwAIovqADHOLP38myeJ5Y3
"""

# Day 9: Rock, Paper, Scissors Game
# Author: Janani Thaddi

import random

print("🎮 Welcome to Rock, Paper, Scissors Game!")

options = ["rock", "paper", "scissors"]

while True:
    print("\nOptions: rock ✊, paper ✋, scissors ✌️")
    user_choice = input("Enter your choice: ").lower()

    if user_choice not in options:
        print("⚠️ Invalid choice. Try again!")
        continue

    computer_choice = random.choice(options)
    print(f"Computer chose: {computer_choice}")

    if user_choice == computer_choice:
        print("😐 It's a draw!")
    elif (
        (user_choice == "rock" and computer_choice == "scissors")
        or (user_choice == "paper" and computer_choice == "rock")
        or (user_choice == "scissors" and computer_choice == "paper")
    ):
        print("🏆 You win!")
    else:
        print("😢 You lose!")

    again = input("\nPlay again? (yes/no): ").lower()
    if again != "yes":
        print("👋 Thanks for playing! See you tomorrow!")
        break

