# -*- coding: utf-8 -*-
"""day11_file_organizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fxzgzT0Epqy8g0Pxy5oVV2Y_91n1tUkR
"""

import os
import shutil

# Folder to organize (you can change this to any path)
source_folder = input("Enter the path of the folder to organize: ").strip()

# Define folder categories
categories = {
    "Images": [".jpg", ".jpeg", ".png", ".gif"],
    "Documents": [".pdf", ".docx", ".txt", ".pptx", ".xlsx"],
    "Videos": [".mp4", ".mkv", ".mov"],
    "Music": [".mp3", ".wav"],
}

# Create category folders if they don't exist
for folder in categories.keys():
    folder_path = os.path.join(source_folder, folder)
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)

# Move files to appropriate folders
for file in os.listdir(source_folder):
    file_path = os.path.join(source_folder, file)
    if os.path.isfile(file_path):
        file_ext = os.path.splitext(file)[1].lower()
        moved = False
        for folder, extensions in categories.items():
            if file_ext in extensions:
                shutil.move(file_path, os.path.join(source_folder, folder, file))
                moved = True
                break
        if not moved:
            other_folder = os.path.join(source_folder, "Others")
            if not os.path.exists(other_folder):
                os.makedirs(other_folder)
            shutil.move(file_path, os.path.join(other_folder, file))

print("✅ Files organized successfully!")