# -*- coding: utf-8 -*-
"""ay10_quiz_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzeXqfDzj6jDIadNwGuWYPNCs3CqlzVE
"""

# Day 10: Simple Quiz App
# Author: Janani Thaddi

print("🧠 Welcome to the Python Quiz Game!")

questions = {
    "What is the capital of France? ": "paris",
    "Which planet is known as the Red Planet? ": "mars",
    "Who wrote 'Harry Potter'? ": "j.k. rowling",
    "What is 5 + 7? ": "12",
    "What is the color of the sky? ": "blue"
}

score = 0

for question, answer in questions.items():
    user_answer = input(question).strip().lower()
    if user_answer == answer:
        print("✅ Correct!")
        score += 1
    else:
        print(f"❌ Wrong! The correct answer is {answer.title()}.")

print("\n🎯 Quiz Completed!")
print(f"Your final score: {score}/{len(questions)}")

if score == len(questions):
    print("🏆 Excellent! Perfect score!")
elif score >= 3:
    print("👏 Good job!")
else:
    print("💡 Keep practicing and try again!")