# -*- coding: utf-8 -*-
"""day10_quiz_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vSBaX1ZJcqQusIIkWczc0VPI9mK8YYDS
"""

# Day 10: Quiz App

def run_quiz():
    print("Welcome to the Python Quiz App!\n")

    questions = [
        {
            "question": "1. What is the capital of France?",
            "options": ["A. Berlin", "B. Madrid", "C. Paris", "D. Rome"],
            "answer": "C"
        },
        {
            "question": "2. Who developed Python?",
            "options": ["A. Elon Musk", "B. Guido van Rossum", "C. Bill Gates", "D. Linus Torvalds"],
            "answer": "B"
        },
        {
            "question": "3. Which data type is immutable in Python?",
            "options": ["A. List", "B. Set", "C. Dictionary", "D. Tuple"],
            "answer": "D"
        }
    ]

    score = 0

    for q in questions:
        print(q["question"])
        for opt in q["options"]:
            print(opt)
        user_answer = input("Your answer (A/B/C/D): ").upper()
        if user_answer == q["answer"]:
            print("✅ Correct!\n")
            score += 1
        else:
            print(f"❌ Wrong! The correct answer was {q['answer']}.\n")

    print(f"🎉 You got {score}/{len(questions)} correct!")

if __name__ == "__main__":
    run_quiz()

